<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<style>
.formulario {
  padding-left:  50px;
  padding-right: 50px;
  margin-left:   50px;
  margin-right:  50px;
  border: 1px solid black;
}
.button{
    margin: 20px;
    grid-template-columns: auto 200px;
}
.button_save{
    background-image: none;
    background: #1979c3;
    border: 1px solid #1979c3;
    color: #ffffff;
}
</style>

<div class= formulario>
<h3>New blog post</h3>
<form class="form" action="<?php echo $block->getUrl('blog/index/save') ?>" method="post" data-hasrequired="* Required Fields" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label for="titulo" class="label"><span>Titulo</span></label>
            <div class="control">
                <input type="text" id="titulo" name="titulo" placeholder="Titulo" class="input-text" data-validate='{"required":true}'>
            </div>
        </div>
        <div class="field name required">
            <label for="contenido" class="label"><span>Contenido</span></label>
            <div class="control">
                <input type="textarea" id="contenido" name="contenido" placeholder="Here all my import text!" class="input-text" data-validate='{"required":true}'>
            </div>
        </div>
        <div class="field name required">
            <label for="email" class="label"><span>Email</span></label>
            <div class="control">
                <input type="text" id="email" name="email" placeholder="email" class="input-text" data-validate='{"required":true}'>
            </div>
        </div>
        <div class="field name">
            <label for="img" class="label"><span>Img</span></label>
            <div class="control">
                <input type="text" id="img" name="img" placeholder="img" class="input-text">
            </div>
        </div>
    </fieldset>
        <div class="button">
               <button class="button_save" title="Guardar Post" placeholder="My Post title">
                  Guardar Post  
                </button>
        </div>
</form>

</div>

    
