<?php
/** @var \OmniPro\Linaoll\Block\Template $block */
?>
 <div class="icono icon"></div>
<div class="container">
    <section id="ingreso-tabs">
        <button id="tab-ingreso">INGRESO</button>
        <button id="tab-registro">REGISTRO</button>
    </section>

    <section id="ingreso-content">
        <div class="tab-content" id="ingreso">
            <form>
                <label for="email">EMAIL</label>
                <input type="email" id="email">
                <label for="password">CONTRASEÑA</label>
                <input type="password" id="password">
                <input type="checkbox" id="subscribe">
                <label for="subscribe">Subscribirse al Newsletter</label>
                <button type="submit">Ingreso</button>
                <a href="#" class="btn btn-success">Olvide contraseña</a>
            </form>
        </div>
        <div class="tab-content" id="registro">
            <form>
                <label for="firstname">NOMBRE</label>
                <input type="text" id="firstname">
                <label for="lastname">APELLIDO</label>
                <input type="text" id="lastname">
                <label for="email-register">EMAIL</label>
                <input type="email" id="email-register">
                <label for="password-register">CONTRASEÑA</label>
                <input type="password" id="password-register">
                <button type="submit">Registro</button>
            </form>
        </div>
    </section>
</div>